In [1]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding

In [2]:
# source text
data = """ AI stands for Artificial Intelligence, which refers to the development of computer systems that can perform tasks that would normally require human intelligence\n
AI involves the use of machine learning algorithms, which enable the system to learn from data inputs and improve its performance over time\n
Other techniques used in AI include natural language processing, robotics, expert systems, and computer vision\n """

In [3]:
# integer encode text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded_data= tokenizer.texts_to_sequences([data])[0]
encoded_data

[1,
 11,
 12,
 13,
 3,
 4,
 14,
 5,
 2,
 15,
 6,
 7,
 8,
 9,
 16,
 17,
 18,
 9,
 19,
 20,
 21,
 22,
 3,
 1,
 23,
 2,
 24,
 6,
 25,
 26,
 27,
 4,
 28,
 2,
 29,
 5,
 30,
 31,
 32,
 33,
 10,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 1,
 43,
 44,
 45,
 46,
 47,
 48,
 8,
 10,
 7,
 49]

In [4]:
# determine the vocabulary size
vocab_size = len(tokenizer.word_index) + 1  # 0 is reserved for padding so that's why we added 1

print('Vocabulary Size: %d' % vocab_size)

Vocabulary Size: 50


# Next, we need to create sequences of words to fit the model with one word as input and one word as output.

In [5]:
# create word -> word sequences
sequences = list()
for i in range(1, len(encoded_data)):
	sequence = encoded_data[i-1:i+1]
	sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))
# split into X and y elements

Total Sequences: 60


# Running this piece shows that we have a total of 60 input-output pairs to train the network

In [6]:
sequences
#sequences[:5] # [input, output]

[[1, 11],
 [11, 12],
 [12, 13],
 [13, 3],
 [3, 4],
 [4, 14],
 [14, 5],
 [5, 2],
 [2, 15],
 [15, 6],
 [6, 7],
 [7, 8],
 [8, 9],
 [9, 16],
 [16, 17],
 [17, 18],
 [18, 9],
 [9, 19],
 [19, 20],
 [20, 21],
 [21, 22],
 [22, 3],
 [3, 1],
 [1, 23],
 [23, 2],
 [2, 24],
 [24, 6],
 [6, 25],
 [25, 26],
 [26, 27],
 [27, 4],
 [4, 28],
 [28, 2],
 [2, 29],
 [29, 5],
 [5, 30],
 [30, 31],
 [31, 32],
 [32, 33],
 [33, 10],
 [10, 34],
 [34, 35],
 [35, 36],
 [36, 37],
 [37, 38],
 [38, 39],
 [39, 40],
 [40, 41],
 [41, 42],
 [42, 1],
 [1, 43],
 [43, 44],
 [44, 45],
 [45, 46],
 [46, 47],
 [47, 48],
 [48, 8],
 [8, 10],
 [10, 7],
 [7, 49]]

# We can then split the sequences into input (X) and output elements (y)

In [7]:
sequences = array(sequences)
X, y = sequences[:,0],sequences[:,1]

In [8]:
X[:5]

array([ 1, 11, 12, 13,  3])

In [9]:

y[:5]

array([11, 12, 13,  3,  4])

In [10]:
# one hot encode outputs
y = to_categorical(y, num_classes=vocab_size)
# define model
y[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [11]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1, 10)             500       
                                                                 
 lstm (LSTM)                 (None, 50)                12200     
                                                                 
 dense (Dense)               (None, 50)                2550      
                                                                 
Total params: 15,250
Trainable params: 15,250
Non-trainable params: 0
_________________________________________________________________
None


In [12]:
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
# fit network
model.fit(X, y, epochs=100)

Epoch 1/100
2/2 [==============================] - 5s 15ms/step - loss: 3.9117 - accuracy: 0.0500
Epoch 2/100
2/2 [==============================] - 0s 10ms/step - loss: 3.9106 - accuracy: 0.0500
Epoch 3/100
2/2 [==============================] - 0s 10ms/step - loss: 3.9097 - accuracy: 0.0333
Epoch 4/100
2/2 [==============================] - 0s 10ms/step - loss: 3.9089 - accuracy: 0.0500
Epoch 5/100
2/2 [==============================] - 0s 9ms/step - loss: 3.9081 - accuracy: 0.0833
Epoch 6/100
2/2 [==============================] - 0s 9ms/step - loss: 3.9073 - accuracy: 0.0833
Epoch 7/100
2/2 [==============================] - 0s 9ms/step - loss: 3.9065 - accuracy: 0.0833
Epoch 8/100
2/2 [==============================] - 0s 8ms/step - loss: 3.9056 - accuracy: 0.0833
Epoch 9/100
2/2 [==============================] - 0s 10ms/step - loss: 3.9047 - accuracy: 0.0833
Epoch 10/100
2/2 [==============================] - 0s 9ms/step - loss: 3.9039 - accuracy: 0.0833
Epoch 11/100
2/2 [======

In [33]:
import numpy as np

def generate_seq(model, tokenizer, enter_text, n_pred):  
    in_text, result = enter_text, enter_text
    
    for _ in range(n_pred):
        # encode the text as integer
        encoded = tokenizer.texts_to_sequences([in_text])[0]
        encoded = np.array(encoded)
        
        # predict probabilities for each word in the vocabulary
        yhat = model.predict(encoded)[0]
        
        # get index of highest probability
        pred_index = np.argmax(yhat)
        
        # map predicted word index to word
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == pred_index:
                out_word = word
                break
                
        # append to input
        in_text, result = out_word, result + ' ' + out_word
        
    return result


In [25]:
from keras.utils import pad_sequences

In [34]:
# evaluate
print(generate_seq(model, tokenizer, 'AI', 6))

1/1 [==============================] - 0s 27ms/step
AI systems and computer systems and computer


In [35]:
# evaluate
print(generate_seq(model, tokenizer, 'machine', 3))

1/1 [==============================] - 0s 36ms/step
machine the development of
